//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.225
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets08831DF0BB9D91FF7310F4CAFCBC7647928B6BA8E7F9BD5EF7BCB84F47E9BA1C))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// 型にはデザイン時に生成された EntitySets および AssociationSets のビューが含まれています。
    /// </Summary>
    public sealed class ViewsForBaseEntitySets08831DF0BB9D91FF7310F4CAFCBC7647928B6BA8E7F9BD5EF7BCB84F47E9BA1C : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// コンストラクターには、エクステントのビューだけでなく、メタデータおよびマッピング クロージャとビューに基づいて生成されたハッシュ値も格納されます。
        /// </Summary>
        public ViewsForBaseEntitySets08831DF0BB9D91FF7310F4CAFCBC7647928B6BA8E7F9BD5EF7BCB84F47E9BA1C()
        {
            this.EdmEntityContainerName = "Entities";
            this.StoreEntityContainerName = "DataModelStoreContainer";
            this.HashOverMappingClosure = "ca42b23b1f348c300b96dbbc1e89c056dce549258a8934776b53d157eea9089d";
            this.HashOverAllExtentViews = "8fbe757a97df4b846ff95f73e3a991188488eb82d1e727ee366cc3cf472c0af7";
            this.ViewCount = 53;
        }
        
        /// <Summary>
        /// このメソッドは、指定されたインデックスのビューを返します。
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            if ((index == 22))
            {
                return GetView22();
            }
            if ((index == 23))
            {
                return GetView23();
            }
            if ((index == 24))
            {
                return GetView24();
            }
            if ((index == 25))
            {
                return GetView25();
            }
            if ((index == 26))
            {
                return GetView26();
            }
            if ((index == 27))
            {
                return GetView27();
            }
            if ((index == 28))
            {
                return GetView28();
            }
            if ((index == 29))
            {
                return GetView29();
            }
            if ((index == 30))
            {
                return GetView30();
            }
            if ((index == 31))
            {
                return GetView31();
            }
            if ((index == 32))
            {
                return GetView32();
            }
            if ((index == 33))
            {
                return GetView33();
            }
            if ((index == 34))
            {
                return GetView34();
            }
            if ((index == 35))
            {
                return GetView35();
            }
            if ((index == 36))
            {
                return GetView36();
            }
            if ((index == 37))
            {
                return GetView37();
            }
            if ((index == 38))
            {
                return GetView38();
            }
            if ((index == 39))
            {
                return GetView39();
            }
            if ((index == 40))
            {
                return GetView40();
            }
            if ((index == 41))
            {
                return GetView41();
            }
            if ((index == 42))
            {
                return GetView42();
            }
            if ((index == 43))
            {
                return GetView43();
            }
            if ((index == 44))
            {
                return GetView44();
            }
            if ((index == 45))
            {
                return GetView45();
            }
            if ((index == 46))
            {
                return GetView46();
            }
            if ((index == 47))
            {
                return GetView47();
            }
            if ((index == 48))
            {
                return GetView48();
            }
            if ((index == 49))
            {
                return GetView49();
            }
            if ((index == 50))
            {
                return GetView50();
            }
            if ((index == 51))
            {
                return GetView51();
            }
            if ((index == 52))
            {
                return GetView52();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// DataModelStoreContainer.Barriers のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.Barriers", @"
    SELECT VALUE -- Constructing Barriers
        [DataModel.Store.Barriers](T1.Barriers_Id, T1.Barriers_Name, T1.Barriers_Comment, T1.Barriers_StartDate, T1.Barriers_FinishDate, T1.Barriers_Geometry, T1.Barriers_BarrierType, T1.Barriers_CreationTime)
    FROM (
        SELECT 
            T.Id AS Barriers_Id, 
            T.Name AS Barriers_Name, 
            T.Comment AS Barriers_Comment, 
            T.StartDate AS Barriers_StartDate, 
            T.FinishDate AS Barriers_FinishDate, 
            T.Geometry AS Barriers_Geometry, 
            T.BarrierType AS Barriers_BarrierType, 
            T.CreationTime AS Barriers_CreationTime, 
            True AS _from0
        FROM Entities.Barriers AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// Entities.Barriers のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.Barriers", @"
    SELECT VALUE -- Constructing Barriers
        [DataModel.Barriers](T1.Barriers_Id, T1.Barriers_Name, T1.Barriers_Comment, T1.Barriers_StartDate, T1.Barriers_FinishDate, T1.Barriers_Geometry, T1.Barriers_BarrierType, T1.Barriers_CreationTime)
    FROM (
        SELECT 
            T.Id AS Barriers_Id, 
            T.Name AS Barriers_Name, 
            T.Comment AS Barriers_Comment, 
            T.StartDate AS Barriers_StartDate, 
            T.FinishDate AS Barriers_FinishDate, 
            T.Geometry AS Barriers_Geometry, 
            T.BarrierType AS Barriers_BarrierType, 
            T.CreationTime AS Barriers_CreationTime, 
            True AS _from0
        FROM DataModelStoreContainer.Barriers AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.ConfigSchemes のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.ConfigSchemes", @"
    SELECT VALUE -- Constructing ConfigSchemes
        [DataModel.Store.ConfigSchemes](T1.ConfigSchemes_Id, T1.ConfigSchemes_Name, T1.ConfigSchemes_Value)
    FROM (
        SELECT 
            T.Id AS ConfigSchemes_Id, 
            T.Name AS ConfigSchemes_Name, 
            T.[Value] AS ConfigSchemes_Value, 
            True AS _from0
        FROM Entities.ConfigSchemes AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// Entities.ConfigSchemes のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.ConfigSchemes", @"
    SELECT VALUE -- Constructing ConfigSchemes
        [DataModel.ConfigSchemes](T1.ConfigSchemes_Id, T1.ConfigSchemes_Name, T1.ConfigSchemes_Value)
    FROM (
        SELECT 
            T.Id AS ConfigSchemes_Id, 
            T.Name AS ConfigSchemes_Name, 
            T.[Value] AS ConfigSchemes_Value, 
            True AS _from0
        FROM DataModelStoreContainer.ConfigSchemes AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.Drivers のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.Drivers", "\r\n    SELECT VALUE -- Constructing Drivers\r\n        [DataModel.Store.Drivers](T3." +
                    "Drivers_Id, T3.Drivers_Name, T3.Drivers_Comment, T3.Drivers_FixedSalary, T3.Driv" +
                    "ers_PerHourSalary, T3.Drivers_PerHourOTSalary, T3.Drivers_TimeBeforeOT, T3.Drive" +
                    "rs_MobileDeviceId, T3.Drivers_CreationTime, T3.Drivers_Deleted)\r\n    FROM (\r\n   " +
                    "     SELECT T1.Drivers_Id, T1.Drivers_Name, T1.Drivers_Comment, T1.Drivers_Fixed" +
                    "Salary, T1.Drivers_PerHourSalary, T1.Drivers_PerHourOTSalary, T1.Drivers_TimeBef" +
                    "oreOT, T2.Drivers_MobileDeviceId, T1.Drivers_CreationTime, T1.Drivers_Deleted, T" +
                    "1._from0, (T2._from1 AND T2._from1 IS NOT NULL) AS _from1\r\n        FROM  (\r\n    " +
                    "        SELECT \r\n                T.Id AS Drivers_Id, \r\n                T.Name AS" +
                    " Drivers_Name, \r\n                T.Comment AS Drivers_Comment, \r\n               " +
                    " T.FixedSalary AS Drivers_FixedSalary, \r\n                T.PerHourSalary AS Driv" +
                    "ers_PerHourSalary, \r\n                T.PerHourOTSalary AS Drivers_PerHourOTSalar" +
                    "y, \r\n                T.TimeBeforeOT AS Drivers_TimeBeforeOT, \r\n                T" +
                    ".CreationTime AS Drivers_CreationTime, \r\n                T.Deleted AS Drivers_De" +
                    "leted, \r\n                True AS _from0\r\n            FROM Entities.Drivers AS T)" +
                    " AS T1\r\n            LEFT OUTER JOIN (\r\n            SELECT \r\n                Key(" +
                    "T.Drivers).Id AS Drivers_Id, \r\n                Key(T.MobileDevices).Id AS Driver" +
                    "s_MobileDeviceId, \r\n                True AS _from1\r\n            FROM Entities.FK" +
                    "_Drivers_MobileDevices AS T) AS T2\r\n            ON T1.Drivers_Id = T2.Drivers_Id" +
                    "\r\n    ) AS T3");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.DriverSpecialties のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.DriverSpecialties", @"
    SELECT VALUE -- Constructing DriverSpecialties
        [DataModel.Store.DriverSpecialties](T1.DriverSpecialties_Id, T1.DriverSpecialties_Name, T1.DriverSpecialties_Comment, T1.DriverSpecialties_CreationTime, T1.DriverSpecialties_Deleted)
    FROM (
        SELECT 
            T.Id AS DriverSpecialties_Id, 
            T.Name AS DriverSpecialties_Name, 
            T.Comment AS DriverSpecialties_Comment, 
            T.CreationTime AS DriverSpecialties_CreationTime, 
            T.Deleted AS DriverSpecialties_Deleted, 
            True AS _from0
        FROM Entities.DriverSpecialties AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.FuelTypes のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.FuelTypes", @"
    SELECT VALUE -- Constructing FuelTypes
        [DataModel.Store.FuelTypes](T1.FuelTypes_Id, T1.FuelTypes_Name, T1.FuelTypes_Price, T1.FuelTypes_Co2Emission, T1.FuelTypes_CreationTime, T1.FuelTypes_Deleted)
    FROM (
        SELECT 
            T.Id AS FuelTypes_Id, 
            T.Name AS FuelTypes_Name, 
            T.Price AS FuelTypes_Price, 
            T.Co2Emission AS FuelTypes_Co2Emission, 
            T.CreationTime AS FuelTypes_CreationTime, 
            T.Deleted AS FuelTypes_Deleted, 
            True AS _from0
        FROM Entities.FuelTypes AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.Locations のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.Locations", "\r\n    SELECT VALUE -- Constructing Locations\r\n        [DataModel.Store.Locations]" +
                    "(T1.Locations_Id, T1.Locations_Name, T1.Locations_Comment, T1.Locations_OpenFrom" +
                    ", T1.Locations_OpenTo, T1.Locations_OpenFrom2, T1.Locations_OpenTo2, T1.Location" +
                    "s_FullAddress, T1.Locations_Unit, T1.Locations_AddressLine, T1.Locations_Localit" +
                    "y1, T1.Locations_Locality2, T1.Locations_Locality3, T1.Locations_CountyPrefectur" +
                    "e, T1.Locations_PostalCode1, T1.Locations_PostalCode2, T1.Locations_StateProvinc" +
                    "e, T1.Locations_Country, T1.Locations_X, T1.Locations_Y, T1.Locations_Locator, T" +
                    "1.Locations_CurbApproach, T1.Locations_CreationTime, T1.Locations_Deleted)\r\n    " +
                    "FROM (\r\n        SELECT \r\n            T.Id AS Locations_Id, \r\n            T.Name " +
                    "AS Locations_Name, \r\n            T.Comment AS Locations_Comment, \r\n            T" +
                    ".OpenFrom AS Locations_OpenFrom, \r\n            T.OpenTo AS Locations_OpenTo, \r\n " +
                    "           T.OpenFrom2 AS Locations_OpenFrom2, \r\n            T.OpenTo2 AS Locati" +
                    "ons_OpenTo2, \r\n            T.FullAddress AS Locations_FullAddress, \r\n           " +
                    " T.Unit AS Locations_Unit, \r\n            T.AddressLine AS Locations_AddressLine," +
                    " \r\n            T.Locality1 AS Locations_Locality1, \r\n            T.Locality2 AS " +
                    "Locations_Locality2, \r\n            T.Locality3 AS Locations_Locality3, \r\n       " +
                    "     T.CountyPrefecture AS Locations_CountyPrefecture, \r\n            T.PostalCod" +
                    "e1 AS Locations_PostalCode1, \r\n            T.PostalCode2 AS Locations_PostalCode" +
                    "2, \r\n            T.StateProvince AS Locations_StateProvince, \r\n            T.Cou" +
                    "ntry AS Locations_Country, \r\n            T.X AS Locations_X, \r\n            T.Y A" +
                    "S Locations_Y, \r\n            T.Locator AS Locations_Locator, \r\n            T.Cur" +
                    "bApproach AS Locations_CurbApproach, \r\n            T.CreationTime AS Locations_C" +
                    "reationTime, \r\n            T.Deleted AS Locations_Deleted, \r\n            True AS" +
                    " _from0\r\n        FROM Entities.Locations AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.MobileDevices のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.MobileDevices", @"
    SELECT VALUE -- Constructing MobileDevices
        [DataModel.Store.MobileDevices](T1.MobileDevices_Id, T1.MobileDevices_Name, T1.MobileDevices_ActiveSyncProfileName, T1.MobileDevices_EmailAddress, T1.MobileDevices_SyncFolder, T1.MobileDevices_SyncType, T1.MobileDevices_CreationTime, T1.MobileDevices_Deleted)
    FROM (
        SELECT 
            T.Id AS MobileDevices_Id, 
            T.Name AS MobileDevices_Name, 
            T.ActiveSyncProfileName AS MobileDevices_ActiveSyncProfileName, 
            T.EmailAddress AS MobileDevices_EmailAddress, 
            T.SyncFolder AS MobileDevices_SyncFolder, 
            T.SyncType AS MobileDevices_SyncType, 
            T.CreationTime AS MobileDevices_CreationTime, 
            T.Deleted AS MobileDevices_Deleted, 
            True AS _from0
        FROM Entities.MobileDevices AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.Orders のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2149);
            viewString.Append("\r\n    SELECT VALUE -- Constructing Orders\r\n        [DataModel.Store.Orders](T1.O");
            viewString.Append("rders_Id, T1.Orders_Name, T1.Orders_PlannedDate, T1.Orders_Locator, T1.Orders_Fu");
            viewString.Append("llAddress, T1.Orders_Unit, T1.Orders_AddressLine, T1.Orders_Locality1, T1.Orders");
            viewString.Append("_Locality2, T1.Orders_Locality3, T1.Orders_CountyPrefecture, T1.Orders_PostalCod");
            viewString.Append("e1, T1.Orders_PostalCode2, T1.Orders_StateProvince, T1.Orders_Country, T1.Orders");
            viewString.Append("_X, T1.Orders_Y, T1.Orders_OrderType, T1.Orders_OrderPriority, T1.Orders_Service");
            viewString.Append("Time, T1.Orders_CurbApproach, T1.Orders_TW1From, T1.Orders_TW1To, T1.Orders_TW2F");
            viewString.Append("rom, T1.Orders_TW2To, T1.Orders_Capacities, T1.Orders_CustomProperties, T1.Order");
            viewString.Append("s_MaxViolationTime, T1.Orders_CreationTime)\r\n    FROM (\r\n        SELECT \r\n      ");
            viewString.Append("      T.Id AS Orders_Id, \r\n            T.Name AS Orders_Name, \r\n            T.Pl");
            viewString.Append("annedDate AS Orders_PlannedDate, \r\n            T.Locator AS Orders_Locator, \r\n  ");
            viewString.Append("          T.FullAddress AS Orders_FullAddress, \r\n            T.Unit AS Orders_Un");
            viewString.Append("it, \r\n            T.AddressLine AS Orders_AddressLine, \r\n            T.Locality1");
            viewString.Append(" AS Orders_Locality1, \r\n            T.Locality2 AS Orders_Locality2, \r\n         ");
            viewString.Append("   T.Locality3 AS Orders_Locality3, \r\n            T.CountyPrefecture AS Orders_C");
            viewString.Append("ountyPrefecture, \r\n            T.PostalCode1 AS Orders_PostalCode1, \r\n          ");
            viewString.Append("  T.PostalCode2 AS Orders_PostalCode2, \r\n            T.StateProvince AS Orders_S");
            viewString.Append("tateProvince, \r\n            T.Country AS Orders_Country, \r\n            T.X AS Or");
            viewString.Append("ders_X, \r\n            T.Y AS Orders_Y, \r\n            T.OrderType AS Orders_Order");
            viewString.Append("Type, \r\n            T.OrderPriority AS Orders_OrderPriority, \r\n            T.Ser");
            viewString.Append("viceTime AS Orders_ServiceTime, \r\n            T.CurbApproach AS Orders_CurbAppro");
            viewString.Append("ach, \r\n            T.TW1From AS Orders_TW1From, \r\n            T.TW1To AS Orders_");
            viewString.Append("TW1To, \r\n            T.TW2From AS Orders_TW2From, \r\n            T.TW2To AS Order");
            viewString.Append("s_TW2To, \r\n            T.Capacities AS Orders_Capacities, \r\n            T.Custom");
            viewString.Append("Properties AS Orders_CustomProperties, \r\n            T.MaxViolationTime AS Order");
            viewString.Append("s_MaxViolationTime, \r\n            T.CreationTime AS Orders_CreationTime, \r\n     ");
            viewString.Append("       True AS _from0\r\n        FROM Entities.Orders AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.Orders", viewString.ToString());
        }
        
        /// <Summary>
        /// DataModelStoreContainer.Routes のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(5097);
            viewString.Append("\r\n    SELECT VALUE -- Constructing Routes\r\n        [DataModel.Store.Routes](T7.R");
            viewString.Append("outes_Id, T7.Routes_Name, T7.Routes_WorkFrom, T7.Routes_WorkTo, T7.Routes_Breaks");
            viewString.Append(", T7.Routes_TimeAtStart, T7.Routes_TimeAtEnd, T7.Routes_TimeAtRenewal, T7.Routes");
            viewString.Append("_MaxOrders, T7.Routes_MaxTravelDistance, T7.Routes_MaxTravelDuration, T7.Routes_");
            viewString.Append("MaxTotalDuration, T7.Routes_Color, T7.Routes_Comment, T7.Routes_Default, T7.Rout");
            viewString.Append("es_Days, T7.Routes_Cost, T7.Routes_StartTime, T7.Routes_EndTime, T7.Routes_Overt");
            viewString.Append("ime, T7.Routes_TotalTime, T7.Routes_TotalDistance, T7.Routes_TravelTime, T7.Rout");
            viewString.Append("es_ViolationTime, T7.Routes_WaitTime, T7.Routes_Capacities, T7.Routes_Locked, T7");
            viewString.Append(".Routes_Visible, T7.Routes_HardZones, T7.Routes_CreationTime, T7.Routes_Vehicles");
            viewString.Append("Id, T7.Routes_DriversId, T7.Routes_StartLocationId, T7.Routes_EndLocationId, T7.");
            viewString.Append("Routes_DefaultRouteID, T7.Routes_ScheduleId)\r\n    FROM (\r\n        SELECT T1.Rout");
            viewString.Append("es_Id, T1.Routes_Name, T1.Routes_WorkFrom, T1.Routes_WorkTo, T1.Routes_Breaks, T");
            viewString.Append("1.Routes_TimeAtStart, T1.Routes_TimeAtEnd, T1.Routes_TimeAtRenewal, T1.Routes_Ma");
            viewString.Append("xOrders, T1.Routes_MaxTravelDistance, T1.Routes_MaxTravelDuration, T1.Routes_Max");
            viewString.Append("TotalDuration, T1.Routes_Color, T1.Routes_Comment, T1.Routes_Default, T1.Routes_");
            viewString.Append("Days, T1.Routes_Cost, T1.Routes_StartTime, T1.Routes_EndTime, T1.Routes_Overtime");
            viewString.Append(", T1.Routes_TotalTime, T1.Routes_TotalDistance, T1.Routes_TravelTime, T1.Routes_");
            viewString.Append("ViolationTime, T1.Routes_WaitTime, T1.Routes_Capacities, T1.Routes_Locked, T1.Ro");
            viewString.Append("utes_Visible, T1.Routes_HardZones, T1.Routes_CreationTime, T3.Routes_VehiclesId,");
            viewString.Append(" T2.Routes_DriversId, T4.Routes_StartLocationId, T6.Routes_EndLocationId, T1.Rou");
            viewString.Append("tes_DefaultRouteID, T5.Routes_ScheduleId, T1._from0, (T2._from1 AND T2._from1 IS");
            viewString.Append(" NOT NULL) AS _from1, (T6._from2 AND T6._from2 IS NOT NULL) AS _from2, (T4._from");
            viewString.Append("3 AND T4._from3 IS NOT NULL) AS _from3, (T5._from4 AND T5._from4 IS NOT NULL) AS");
            viewString.Append(" _from4, (T3._from5 AND T3._from5 IS NOT NULL) AS _from5\r\n        FROM  (\r\n     ");
            viewString.Append("       SELECT \r\n                T.Id AS Routes_Id, \r\n                T.Name AS R");
            viewString.Append("outes_Name, \r\n                T.WorkFrom AS Routes_WorkFrom, \r\n                T");
            viewString.Append(".WorkTo AS Routes_WorkTo, \r\n                T.Breaks AS Routes_Breaks, \r\n       ");
            viewString.Append("         T.TimeAtStart AS Routes_TimeAtStart, \r\n                T.TimeAtEnd AS R");
            viewString.Append("outes_TimeAtEnd, \r\n                T.TimeAtRenewal AS Routes_TimeAtRenewal, \r\n  ");
            viewString.Append("              T.MaxOrders AS Routes_MaxOrders, \r\n                T.MaxTravelDist");
            viewString.Append("ance AS Routes_MaxTravelDistance, \r\n                T.MaxTravelDuration AS Route");
            viewString.Append("s_MaxTravelDuration, \r\n                T.MaxTotalDuration AS Routes_MaxTotalDura");
            viewString.Append("tion, \r\n                T.Color AS Routes_Color, \r\n                T.Comment AS ");
            viewString.Append("Routes_Comment, \r\n                T.Default AS Routes_Default, \r\n               ");
            viewString.Append(" T.Days AS Routes_Days, \r\n                T.Cost AS Routes_Cost, \r\n             ");
            viewString.Append("   T.StartTime AS Routes_StartTime, \r\n                T.EndTime AS Routes_EndTim");
            viewString.Append("e, \r\n                T.Overtime AS Routes_Overtime, \r\n                T.TotalTim");
            viewString.Append("e AS Routes_TotalTime, \r\n                T.TotalDistance AS Routes_TotalDistance");
            viewString.Append(", \r\n                T.TravelTime AS Routes_TravelTime, \r\n                T.Viola");
            viewString.Append("tionTime AS Routes_ViolationTime, \r\n                T.WaitTime AS Routes_WaitTim");
            viewString.Append("e, \r\n                T.Capacities AS Routes_Capacities, \r\n                T.Lock");
            viewString.Append("ed AS Routes_Locked, \r\n                T.Visible AS Routes_Visible, \r\n          ");
            viewString.Append("      T.HardZones AS Routes_HardZones, \r\n                T.CreationTime AS Route");
            viewString.Append("s_CreationTime, \r\n                T.DefaultRouteID AS Routes_DefaultRouteID, \r\n ");
            viewString.Append("               True AS _from0\r\n            FROM Entities.Routes AS T) AS T1\r\n   ");
            viewString.Append("         LEFT OUTER JOIN (\r\n            SELECT \r\n                Key(T.Routes).I");
            viewString.Append("d AS Routes_Id, \r\n                Key(T.Drivers).Id AS Routes_DriversId, \r\n     ");
            viewString.Append("           True AS _from1\r\n            FROM Entities.FK_Routes_Drivers AS T) AS ");
            viewString.Append("T2\r\n            ON T1.Routes_Id = T2.Routes_Id\r\n            LEFT OUTER JOIN (\r\n ");
            viewString.Append("           SELECT \r\n                Key(T.Routes).Id AS Routes_Id, \r\n           ");
            viewString.Append("     Key(T.Vehicles).Id AS Routes_VehiclesId, \r\n                True AS _from5\r\n");
            viewString.Append("            FROM Entities.FK_Routes_Vehicles AS T) AS T3\r\n            ON T1.Rout");
            viewString.Append("es_Id = T3.Routes_Id\r\n            LEFT OUTER JOIN (\r\n            SELECT \r\n      ");
            viewString.Append("          Key(T.Routes).Id AS Routes_Id, \r\n                Key(T.Locations).Id A");
            viewString.Append("S Routes_StartLocationId, \r\n                True AS _from3\r\n            FROM Ent");
            viewString.Append("ities.FK_Routes_StartLocations AS T) AS T4\r\n            ON T1.Routes_Id = T4.Rou");
            viewString.Append("tes_Id\r\n            LEFT OUTER JOIN (\r\n            SELECT \r\n                Key(");
            viewString.Append("T.Routes).Id AS Routes_Id, \r\n                Key(T.Schedules).Id AS Routes_Sched");
            viewString.Append("uleId, \r\n                True AS _from4\r\n            FROM Entities.FK_Routes_Sch");
            viewString.Append("edules AS T) AS T5\r\n            ON T1.Routes_Id = T5.Routes_Id\r\n            LEFT");
            viewString.Append(" OUTER JOIN (\r\n            SELECT \r\n                Key(T.Routes).Id AS Routes_I");
            viewString.Append("d, \r\n                Key(T.Locations).Id AS Routes_EndLocationId, \r\n            ");
            viewString.Append("    True AS _from2\r\n            FROM Entities.FK_Routes_EndLocations AS T) AS T6");
            viewString.Append("\r\n            ON T1.Routes_Id = T6.Routes_Id\r\n    ) AS T7");
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.Routes", viewString.ToString());
        }
        
        /// <Summary>
        /// DataModelStoreContainer.Schedules のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.Schedules", @"
    SELECT VALUE -- Constructing Schedules
        [DataModel.Store.Schedules](T1.Schedules_Id, T1.Schedules_Name, T1.Schedules_PlannedDate, T1.Schedules_ScheduleType, T1.Schedules_CreationTime)
    FROM (
        SELECT 
            T.Id AS Schedules_Id, 
            T.Name AS Schedules_Name, 
            T.PlannedDate AS Schedules_PlannedDate, 
            T.ScheduleType AS Schedules_ScheduleType, 
            T.CreationTime AS Schedules_CreationTime, 
            True AS _from0
        FROM Entities.Schedules AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.Stops のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2428);
            viewString.Append("\r\n    SELECT VALUE -- Constructing Stops\r\n        [DataModel.Store.Stops](T5.Sto");
            viewString.Append("ps_Id, T5.Stops_ArriveTime, T5.Stops_Directions, T5.Stops_PathTo, T5.Stops_Dista");
            viewString.Append("nce, T5.Stops_SequenceNumber, T5.Stops_OrderSequenceNumber, T5.Stops_Type, T5.St");
            viewString.Append("ops_TimeAtStop, T5.Stops_TravelTime, T5.Stops_WaitTime, T5.Stops_Locked, T5.Stop");
            viewString.Append("s_LocationId, T5.Stops_OrderId, T5.Stops_RouteId)\r\n    FROM (\r\n        SELECT T1");
            viewString.Append(".Stops_Id, T1.Stops_ArriveTime, T1.Stops_Directions, T1.Stops_PathTo, T1.Stops_D");
            viewString.Append("istance, T1.Stops_SequenceNumber, T1.Stops_OrderSequenceNumber, T1.Stops_Type, T");
            viewString.Append("1.Stops_TimeAtStop, T1.Stops_TravelTime, T1.Stops_WaitTime, T1.Stops_Locked, T2.");
            viewString.Append("Stops_LocationId, T4.Stops_OrderId, T3.Stops_RouteId, T1._from0, (T2._from1 AND ");
            viewString.Append("T2._from1 IS NOT NULL) AS _from1, (T4._from2 AND T4._from2 IS NOT NULL) AS _from");
            viewString.Append("2, (T3._from3 AND T3._from3 IS NOT NULL) AS _from3\r\n        FROM  (\r\n           ");
            viewString.Append(" SELECT \r\n                T.Id AS Stops_Id, \r\n                T.ArriveTime AS St");
            viewString.Append("ops_ArriveTime, \r\n                T.Directions AS Stops_Directions, \r\n          ");
            viewString.Append("      T.PathTo AS Stops_PathTo, \r\n                T.Distance AS Stops_Distance, ");
            viewString.Append("\r\n                T.SequenceNumber AS Stops_SequenceNumber, \r\n                T.");
            viewString.Append("OrderSequenceNumber AS Stops_OrderSequenceNumber, \r\n                T.Type AS St");
            viewString.Append("ops_Type, \r\n                T.TimeAtStop AS Stops_TimeAtStop, \r\n                ");
            viewString.Append("T.TravelTime AS Stops_TravelTime, \r\n                T.WaitTime AS Stops_WaitTime");
            viewString.Append(", \r\n                T.Locked AS Stops_Locked, \r\n                True AS _from0\r\n");
            viewString.Append("            FROM Entities.Stops AS T) AS T1\r\n            LEFT OUTER JOIN (\r\n    ");
            viewString.Append("        SELECT \r\n                Key(T.Stops).Id AS Stops_Id, \r\n                ");
            viewString.Append("Key(T.Locations).Id AS Stops_LocationId, \r\n                True AS _from1\r\n     ");
            viewString.Append("       FROM Entities.FK_Stops_Locations AS T) AS T2\r\n            ON T1.Stops_Id ");
            viewString.Append("= T2.Stops_Id\r\n            LEFT OUTER JOIN (\r\n            SELECT \r\n             ");
            viewString.Append("   Key(T.Stops).Id AS Stops_Id, \r\n                Key(T.Routes).Id AS Stops_Rout");
            viewString.Append("eId, \r\n                True AS _from3\r\n            FROM Entities.FK_Stops_Routes");
            viewString.Append(" AS T) AS T3\r\n            ON T1.Stops_Id = T3.Stops_Id\r\n            LEFT OUTER J");
            viewString.Append("OIN (\r\n            SELECT \r\n                Key(T.Stops).Id AS Stops_Id, \r\n     ");
            viewString.Append("           Key(T.Orders).Id AS Stops_OrderId, \r\n                True AS _from2\r\n");
            viewString.Append("            FROM Entities.FK_Stops_Orders AS T) AS T4\r\n            ON T1.Stops_I");
            viewString.Append("d = T4.Stops_Id\r\n    ) AS T5");
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.Stops", viewString.ToString());
        }
        
        /// <Summary>
        /// DataModelStoreContainer.Vehicles のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.Vehicles", "\r\n    SELECT VALUE -- Constructing Vehicles\r\n        [DataModel.Store.Vehicles](T" +
                    "4.Vehicles_Id, T4.Vehicles_Name, T4.Vehicles_Comment, T4.Vehicles_FixedSalary, T" +
                    "4.Vehicles_FuelConsumption, T4.Vehicles_Capacities, T4.Vehicles_MobileDeviceId, " +
                    "T4.Vehicles_FuelTypeId, T4.Vehicles_CreationTime, T4.Vehicles_Deleted)\r\n    FROM" +
                    " (\r\n        SELECT T1.Vehicles_Id, T1.Vehicles_Name, T1.Vehicles_Comment, T1.Veh" +
                    "icles_FixedSalary, T1.Vehicles_FuelConsumption, T1.Vehicles_Capacities, T3.Vehic" +
                    "les_MobileDeviceId, T2.Vehicles_FuelTypeId, T1.Vehicles_CreationTime, T1.Vehicle" +
                    "s_Deleted, T1._from0, (T2._from1 AND T2._from1 IS NOT NULL) AS _from1, (T3._from" +
                    "2 AND T3._from2 IS NOT NULL) AS _from2\r\n        FROM  (\r\n            SELECT \r\n  " +
                    "              T.Id AS Vehicles_Id, \r\n                T.Name AS Vehicles_Name, \r\n" +
                    "                T.Comment AS Vehicles_Comment, \r\n                T.FixedSalary A" +
                    "S Vehicles_FixedSalary, \r\n                T.FuelConsumption AS Vehicles_FuelCons" +
                    "umption, \r\n                T.Capacities AS Vehicles_Capacities, \r\n              " +
                    "  T.CreationTime AS Vehicles_CreationTime, \r\n                T.Deleted AS Vehicl" +
                    "es_Deleted, \r\n                True AS _from0\r\n            FROM Entities.Vehicles" +
                    " AS T) AS T1\r\n            LEFT OUTER JOIN (\r\n            SELECT \r\n              " +
                    "  Key(T.Vehicles).Id AS Vehicles_Id, \r\n                Key(T.FuelTypes).Id AS Ve" +
                    "hicles_FuelTypeId, \r\n                True AS _from1\r\n            FROM Entities.F" +
                    "K_Vehicles_FuelTypes AS T) AS T2\r\n            ON T1.Vehicles_Id = T2.Vehicles_Id" +
                    "\r\n            LEFT OUTER JOIN (\r\n            SELECT \r\n                Key(T.Vehi" +
                    "cles).Id AS Vehicles_Id, \r\n                Key(T.MobileDevices).Id AS Vehicles_M" +
                    "obileDeviceId, \r\n                True AS _from2\r\n            FROM Entities.FK_Ve" +
                    "hicles_MobileDevices AS T) AS T3\r\n            ON T1.Vehicles_Id = T3.Vehicles_Id" +
                    "\r\n    ) AS T4");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.VehicleSpecialties のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.VehicleSpecialties", @"
    SELECT VALUE -- Constructing VehicleSpecialties
        [DataModel.Store.VehicleSpecialties](T1.VehicleSpecialties_Id, T1.VehicleSpecialties_Name, T1.VehicleSpecialties_Comment, T1.VehicleSpecialties_CreationTime, T1.VehicleSpecialties_Deleted)
    FROM (
        SELECT 
            T.Id AS VehicleSpecialties_Id, 
            T.Name AS VehicleSpecialties_Name, 
            T.Comment AS VehicleSpecialties_Comment, 
            T.CreationTime AS VehicleSpecialties_CreationTime, 
            T.Deleted AS VehicleSpecialties_Deleted, 
            True AS _from0
        FROM Entities.VehicleSpecialties AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.Zones のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.Zones", @"
    SELECT VALUE -- Constructing Zones
        [DataModel.Store.Zones](T1.Zones_Id, T1.Zones_Name, T1.Zones_Comment, T1.Zones_Geometry, T1.Zones_CreationTime, T1.Zones_Deleted)
    FROM (
        SELECT 
            T.Id AS Zones_Id, 
            T.Name AS Zones_Name, 
            T.Comment AS Zones_Comment, 
            T.Geometry AS Zones_Geometry, 
            T.CreationTime AS Zones_CreationTime, 
            T.Deleted AS Zones_Deleted, 
            True AS _from0
        FROM Entities.Zones AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.DriverDriverSpecialties のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.DriverDriverSpecialties", @"
    SELECT VALUE -- Constructing DriverDriverSpecialties
        [DataModel.Store.DriverDriverSpecialties](T1.DriverDriverSpecialties_DriverId, T1.DriverDriverSpecialties_DriverSpecialtyId)
    FROM (
        SELECT 
            Key(T.Drivers).Id AS DriverDriverSpecialties_DriverId, 
            Key(T.DriverSpecialties).Id AS DriverDriverSpecialties_DriverSpecialtyId, 
            True AS _from0
        FROM Entities.DriverDriverSpecialties AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.OrderDriverSpecialties のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.OrderDriverSpecialties", @"
    SELECT VALUE -- Constructing OrderDriverSpecialties
        [DataModel.Store.OrderDriverSpecialties](T1.OrderDriverSpecialties_OrderId, T1.OrderDriverSpecialties_DriverSpecialtyId)
    FROM (
        SELECT 
            Key(T.Orders).Id AS OrderDriverSpecialties_OrderId, 
            Key(T.DriverSpecialties).Id AS OrderDriverSpecialties_DriverSpecialtyId, 
            True AS _from0
        FROM Entities.OrderDriverSpecialties AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.OrderVehicleSpecialties のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.OrderVehicleSpecialties", @"
    SELECT VALUE -- Constructing OrderVehicleSpecialties
        [DataModel.Store.OrderVehicleSpecialties](T1.OrderVehicleSpecialties_OrderId, T1.OrderVehicleSpecialties_VehicleSpecialtyId)
    FROM (
        SELECT 
            Key(T.Orders).Id AS OrderVehicleSpecialties_OrderId, 
            Key(T.VehicleSpecialties).Id AS OrderVehicleSpecialties_VehicleSpecialtyId, 
            True AS _from0
        FROM Entities.OrderVehicleSpecialties AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.RenewalLocations のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.RenewalLocations", @"
    SELECT VALUE -- Constructing RenewalLocations
        [DataModel.Store.RenewalLocations](T1.RenewalLocations_RouteId, T1.RenewalLocations_LocationId)
    FROM (
        SELECT 
            Key(T.Routes).Id AS RenewalLocations_RouteId, 
            Key(T.Locations).Id AS RenewalLocations_LocationId, 
            True AS _from0
        FROM Entities.RenewalLocations AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.RouteZones のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.RouteZones", @"
    SELECT VALUE -- Constructing RouteZones
        [DataModel.Store.RouteZones](T1.RouteZones_RouteId, T1.RouteZones_ZoneId)
    FROM (
        SELECT 
            Key(T.Routes).Id AS RouteZones_RouteId, 
            Key(T.Zones).Id AS RouteZones_ZoneId, 
            True AS _from0
        FROM Entities.RouteZones AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.VehicleVehicleSpecialties のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.VehicleVehicleSpecialties", @"
    SELECT VALUE -- Constructing VehicleVehicleSpecialties
        [DataModel.Store.VehicleVehicleSpecialties](T1.VehicleVehicleSpecialties_VehicleId, T1.VehicleVehicleSpecialties_VehicleSpecialtyId)
    FROM (
        SELECT 
            Key(T.Vehicles).Id AS VehicleVehicleSpecialties_VehicleId, 
            Key(T.VehicleSpecialties).Id AS VehicleVehicleSpecialties_VehicleSpecialtyId, 
            True AS _from0
        FROM Entities.VehicleVehicleSpecialties AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// Entities.Drivers のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView22()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.Drivers", @"
    SELECT VALUE -- Constructing Drivers
        [DataModel.Drivers](T1.Drivers_Id, T1.Drivers_Name, T1.Drivers_Comment, T1.Drivers_FixedSalary, T1.Drivers_PerHourSalary, T1.Drivers_PerHourOTSalary, T1.Drivers_TimeBeforeOT, T1.Drivers_CreationTime, T1.Drivers_Deleted) WITH 
        RELATIONSHIP(CREATEREF(Entities.MobileDevices, ROW(T1.[FK_Drivers_MobileDevices.MobileDevices.Id]),[DataModel.MobileDevices]),[DataModel.FK_Drivers_MobileDevices],Drivers,MobileDevices) 
    FROM (
        SELECT 
            T.Id AS Drivers_Id, 
            T.Name AS Drivers_Name, 
            T.Comment AS Drivers_Comment, 
            T.FixedSalary AS Drivers_FixedSalary, 
            T.PerHourSalary AS Drivers_PerHourSalary, 
            T.PerHourOTSalary AS Drivers_PerHourOTSalary, 
            T.TimeBeforeOT AS Drivers_TimeBeforeOT, 
            T.CreationTime AS Drivers_CreationTime, 
            T.Deleted AS Drivers_Deleted, 
            True AS _from0, 
            T.MobileDeviceId AS [FK_Drivers_MobileDevices.MobileDevices.Id]
        FROM DataModelStoreContainer.Drivers AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// Entities.DriverSpecialties のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView23()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.DriverSpecialties", @"
    SELECT VALUE -- Constructing DriverSpecialties
        [DataModel.DriverSpecialties](T1.DriverSpecialties_Id, T1.DriverSpecialties_Name, T1.DriverSpecialties_Comment, T1.DriverSpecialties_CreationTime, T1.DriverSpecialties_Deleted)
    FROM (
        SELECT 
            T.Id AS DriverSpecialties_Id, 
            T.Name AS DriverSpecialties_Name, 
            T.Comment AS DriverSpecialties_Comment, 
            T.CreationTime AS DriverSpecialties_CreationTime, 
            T.Deleted AS DriverSpecialties_Deleted, 
            True AS _from0
        FROM DataModelStoreContainer.DriverSpecialties AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// Entities.FuelTypes のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView24()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.FuelTypes", @"
    SELECT VALUE -- Constructing FuelTypes
        [DataModel.FuelTypes](T1.FuelTypes_Id, T1.FuelTypes_Name, T1.FuelTypes_Price, T1.FuelTypes_Co2Emission, T1.FuelTypes_CreationTime, T1.FuelTypes_Deleted)
    FROM (
        SELECT 
            T.Id AS FuelTypes_Id, 
            T.Name AS FuelTypes_Name, 
            T.Price AS FuelTypes_Price, 
            T.Co2Emission AS FuelTypes_Co2Emission, 
            T.CreationTime AS FuelTypes_CreationTime, 
            T.Deleted AS FuelTypes_Deleted, 
            True AS _from0
        FROM DataModelStoreContainer.FuelTypes AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// Entities.Locations のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView25()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.Locations", "\r\n    SELECT VALUE -- Constructing Locations\r\n        [DataModel.Locations](T1.Lo" +
                    "cations_Id, T1.Locations_Name, T1.Locations_Comment, T1.Locations_OpenFrom, T1.L" +
                    "ocations_OpenTo, T1.Locations_OpenFrom2, T1.Locations_OpenTo2, T1.Locations_Full" +
                    "Address, T1.Locations_Unit, T1.Locations_AddressLine, T1.Locations_Locality1, T1" +
                    ".Locations_Locality2, T1.Locations_Locality3, T1.Locations_CountyPrefecture, T1." +
                    "Locations_PostalCode1, T1.Locations_PostalCode2, T1.Locations_StateProvince, T1." +
                    "Locations_Country, T1.Locations_X, T1.Locations_Y, T1.Locations_Locator, T1.Loca" +
                    "tions_CurbApproach, T1.Locations_CreationTime, T1.Locations_Deleted)\r\n    FROM (" +
                    "\r\n        SELECT \r\n            T.Id AS Locations_Id, \r\n            T.Name AS Loc" +
                    "ations_Name, \r\n            T.Comment AS Locations_Comment, \r\n            T.OpenF" +
                    "rom AS Locations_OpenFrom, \r\n            T.OpenTo AS Locations_OpenTo, \r\n       " +
                    "     T.OpenFrom2 AS Locations_OpenFrom2, \r\n            T.OpenTo2 AS Locations_Op" +
                    "enTo2, \r\n            T.FullAddress AS Locations_FullAddress, \r\n            T.Uni" +
                    "t AS Locations_Unit, \r\n            T.AddressLine AS Locations_AddressLine, \r\n   " +
                    "         T.Locality1 AS Locations_Locality1, \r\n            T.Locality2 AS Locati" +
                    "ons_Locality2, \r\n            T.Locality3 AS Locations_Locality3, \r\n            T" +
                    ".CountyPrefecture AS Locations_CountyPrefecture, \r\n            T.PostalCode1 AS " +
                    "Locations_PostalCode1, \r\n            T.PostalCode2 AS Locations_PostalCode2, \r\n " +
                    "           T.StateProvince AS Locations_StateProvince, \r\n            T.Country A" +
                    "S Locations_Country, \r\n            T.X AS Locations_X, \r\n            T.Y AS Loca" +
                    "tions_Y, \r\n            T.Locator AS Locations_Locator, \r\n            T.CurbAppro" +
                    "ach AS Locations_CurbApproach, \r\n            T.CreationTime AS Locations_Creatio" +
                    "nTime, \r\n            T.Deleted AS Locations_Deleted, \r\n            True AS _from" +
                    "0\r\n        FROM DataModelStoreContainer.Locations AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// Entities.MobileDevices のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView26()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.MobileDevices", @"
    SELECT VALUE -- Constructing MobileDevices
        [DataModel.MobileDevices](T1.MobileDevices_Id, T1.MobileDevices_Name, T1.MobileDevices_ActiveSyncProfileName, T1.MobileDevices_EmailAddress, T1.MobileDevices_SyncFolder, T1.MobileDevices_SyncType, T1.MobileDevices_CreationTime, T1.MobileDevices_Deleted)
    FROM (
        SELECT 
            T.Id AS MobileDevices_Id, 
            T.Name AS MobileDevices_Name, 
            T.ActiveSyncProfileName AS MobileDevices_ActiveSyncProfileName, 
            T.EmailAddress AS MobileDevices_EmailAddress, 
            T.SyncFolder AS MobileDevices_SyncFolder, 
            T.SyncType AS MobileDevices_SyncType, 
            T.CreationTime AS MobileDevices_CreationTime, 
            T.Deleted AS MobileDevices_Deleted, 
            True AS _from0
        FROM DataModelStoreContainer.MobileDevices AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// Entities.Orders のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView27()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2158);
            viewString.Append("\r\n    SELECT VALUE -- Constructing Orders\r\n        [DataModel.Orders](T1.Orders_");
            viewString.Append("Id, T1.Orders_Name, T1.Orders_PlannedDate, T1.Orders_Locator, T1.Orders_FullAddr");
            viewString.Append("ess, T1.Orders_Unit, T1.Orders_AddressLine, T1.Orders_Locality1, T1.Orders_Local");
            viewString.Append("ity2, T1.Orders_Locality3, T1.Orders_CountyPrefecture, T1.Orders_PostalCode1, T1");
            viewString.Append(".Orders_PostalCode2, T1.Orders_StateProvince, T1.Orders_Country, T1.Orders_X, T1");
            viewString.Append(".Orders_Y, T1.Orders_OrderType, T1.Orders_OrderPriority, T1.Orders_ServiceTime, ");
            viewString.Append("T1.Orders_CurbApproach, T1.Orders_TW1From, T1.Orders_TW1To, T1.Orders_TW2From, T");
            viewString.Append("1.Orders_TW2To, T1.Orders_Capacities, T1.Orders_CustomProperties, T1.Orders_MaxV");
            viewString.Append("iolationTime, T1.Orders_CreationTime)\r\n    FROM (\r\n        SELECT \r\n            ");
            viewString.Append("T.Id AS Orders_Id, \r\n            T.Name AS Orders_Name, \r\n            T.PlannedD");
            viewString.Append("ate AS Orders_PlannedDate, \r\n            T.Locator AS Orders_Locator, \r\n        ");
            viewString.Append("    T.FullAddress AS Orders_FullAddress, \r\n            T.Unit AS Orders_Unit, \r\n");
            viewString.Append("            T.AddressLine AS Orders_AddressLine, \r\n            T.Locality1 AS Or");
            viewString.Append("ders_Locality1, \r\n            T.Locality2 AS Orders_Locality2, \r\n            T.L");
            viewString.Append("ocality3 AS Orders_Locality3, \r\n            T.CountyPrefecture AS Orders_CountyP");
            viewString.Append("refecture, \r\n            T.PostalCode1 AS Orders_PostalCode1, \r\n            T.Po");
            viewString.Append("stalCode2 AS Orders_PostalCode2, \r\n            T.StateProvince AS Orders_StatePr");
            viewString.Append("ovince, \r\n            T.Country AS Orders_Country, \r\n            T.X AS Orders_X");
            viewString.Append(", \r\n            T.Y AS Orders_Y, \r\n            T.OrderType AS Orders_OrderType, ");
            viewString.Append("\r\n            T.OrderPriority AS Orders_OrderPriority, \r\n            T.ServiceTi");
            viewString.Append("me AS Orders_ServiceTime, \r\n            T.CurbApproach AS Orders_CurbApproach, \r");
            viewString.Append("\n            T.TW1From AS Orders_TW1From, \r\n            T.TW1To AS Orders_TW1To,");
            viewString.Append(" \r\n            T.TW2From AS Orders_TW2From, \r\n            T.TW2To AS Orders_TW2T");
            viewString.Append("o, \r\n            T.Capacities AS Orders_Capacities, \r\n            T.CustomProper");
            viewString.Append("ties AS Orders_CustomProperties, \r\n            T.MaxViolationTime AS Orders_MaxV");
            viewString.Append("iolationTime, \r\n            T.CreationTime AS Orders_CreationTime, \r\n           ");
            viewString.Append(" True AS _from0\r\n        FROM DataModelStoreContainer.Orders AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.Orders", viewString.ToString());
        }
        
        /// <Summary>
        /// Entities.Routes のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView28()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(3488);
            viewString.Append("\r\n    SELECT VALUE -- Constructing Routes\r\n        [DataModel.Routes](T1.Routes_");
            viewString.Append("Id, T1.Routes_Name, T1.Routes_WorkFrom, T1.Routes_WorkTo, T1.Routes_Breaks, T1.R");
            viewString.Append("outes_TimeAtStart, T1.Routes_TimeAtEnd, T1.Routes_TimeAtRenewal, T1.Routes_MaxOr");
            viewString.Append("ders, T1.Routes_MaxTravelDistance, T1.Routes_MaxTravelDuration, T1.Routes_MaxTot");
            viewString.Append("alDuration, T1.Routes_Color, T1.Routes_Comment, T1.Routes_Default, T1.Routes_Day");
            viewString.Append("s, T1.Routes_Cost, T1.Routes_StartTime, T1.Routes_EndTime, T1.Routes_Overtime, T");
            viewString.Append("1.Routes_TotalTime, T1.Routes_TotalDistance, T1.Routes_TravelTime, T1.Routes_Vio");
            viewString.Append("lationTime, T1.Routes_WaitTime, T1.Routes_Capacities, T1.Routes_Locked, T1.Route");
            viewString.Append("s_Visible, T1.Routes_HardZones, T1.Routes_CreationTime, T1.Routes_DefaultRouteID");
            viewString.Append(") WITH \r\n        RELATIONSHIP(CREATEREF(Entities.Drivers, ROW(T1.[FK_Routes_Driv");
            viewString.Append("ers.Drivers.Id]),[DataModel.Drivers]),[DataModel.FK_Routes_Drivers],Routes,Drive");
            viewString.Append("rs) \r\n        RELATIONSHIP(CREATEREF(Entities.Locations, ROW(T1.[FK_Routes_EndLo");
            viewString.Append("cations.Locations.Id]),[DataModel.Locations]),[DataModel.FK_Routes_EndLocations]");
            viewString.Append(",Routes,Locations) \r\n        RELATIONSHIP(CREATEREF(Entities.Locations, ROW(T1.[");
            viewString.Append("FK_Routes_StartLocations.Locations.Id]),[DataModel.Locations]),[DataModel.FK_Rou");
            viewString.Append("tes_StartLocations],Routes,Locations) \r\n        RELATIONSHIP(CREATEREF(Entities.");
            viewString.Append("Schedules, ROW(T1.[FK_Routes_Schedules.Schedules.Id]),[DataModel.Schedules]),[Da");
            viewString.Append("taModel.FK_Routes_Schedules],Routes,Schedules) \r\n        RELATIONSHIP(CREATEREF(");
            viewString.Append("Entities.Vehicles, ROW(T1.[FK_Routes_Vehicles.Vehicles.Id]),[DataModel.Vehicles]");
            viewString.Append("),[DataModel.FK_Routes_Vehicles],Routes,Vehicles) \r\n    FROM (\r\n        SELECT \r");
            viewString.Append("\n            T.Id AS Routes_Id, \r\n            T.Name AS Routes_Name, \r\n         ");
            viewString.Append("   T.WorkFrom AS Routes_WorkFrom, \r\n            T.WorkTo AS Routes_WorkTo, \r\n   ");
            viewString.Append("         T.Breaks AS Routes_Breaks, \r\n            T.TimeAtStart AS Routes_TimeAt");
            viewString.Append("Start, \r\n            T.TimeAtEnd AS Routes_TimeAtEnd, \r\n            T.TimeAtRene");
            viewString.Append("wal AS Routes_TimeAtRenewal, \r\n            T.MaxOrders AS Routes_MaxOrders, \r\n  ");
            viewString.Append("          T.MaxTravelDistance AS Routes_MaxTravelDistance, \r\n            T.MaxTr");
            viewString.Append("avelDuration AS Routes_MaxTravelDuration, \r\n            T.MaxTotalDuration AS Ro");
            viewString.Append("utes_MaxTotalDuration, \r\n            T.Color AS Routes_Color, \r\n            T.Co");
            viewString.Append("mment AS Routes_Comment, \r\n            T.Default AS Routes_Default, \r\n          ");
            viewString.Append("  T.Days AS Routes_Days, \r\n            T.Cost AS Routes_Cost, \r\n            T.St");
            viewString.Append("artTime AS Routes_StartTime, \r\n            T.EndTime AS Routes_EndTime, \r\n      ");
            viewString.Append("      T.Overtime AS Routes_Overtime, \r\n            T.TotalTime AS Routes_TotalTi");
            viewString.Append("me, \r\n            T.TotalDistance AS Routes_TotalDistance, \r\n            T.Trave");
            viewString.Append("lTime AS Routes_TravelTime, \r\n            T.ViolationTime AS Routes_ViolationTim");
            viewString.Append("e, \r\n            T.WaitTime AS Routes_WaitTime, \r\n            T.Capacities AS Ro");
            viewString.Append("utes_Capacities, \r\n            T.Locked AS Routes_Locked, \r\n            T.Visibl");
            viewString.Append("e AS Routes_Visible, \r\n            T.HardZones AS Routes_HardZones, \r\n          ");
            viewString.Append("  T.CreationTime AS Routes_CreationTime, \r\n            T.DefaultRouteID AS Route");
            viewString.Append("s_DefaultRouteID, \r\n            True AS _from0, \r\n            T.DriversId AS [FK");
            viewString.Append("_Routes_Drivers.Drivers.Id], \r\n            T.EndLocationId AS [FK_Routes_EndLoca");
            viewString.Append("tions.Locations.Id], \r\n            T.StartLocationId AS [FK_Routes_StartLocation");
            viewString.Append("s.Locations.Id], \r\n            T.ScheduleId AS [FK_Routes_Schedules.Schedules.Id");
            viewString.Append("], \r\n            T.VehiclesId AS [FK_Routes_Vehicles.Vehicles.Id]\r\n        FROM ");
            viewString.Append("DataModelStoreContainer.Routes AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.Routes", viewString.ToString());
        }
        
        /// <Summary>
        /// Entities.Schedules のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView29()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.Schedules", @"
    SELECT VALUE -- Constructing Schedules
        [DataModel.Schedules](T1.Schedules_Id, T1.Schedules_Name, T1.Schedules_PlannedDate, T1.Schedules_ScheduleType, T1.Schedules_CreationTime)
    FROM (
        SELECT 
            T.Id AS Schedules_Id, 
            T.Name AS Schedules_Name, 
            T.PlannedDate AS Schedules_PlannedDate, 
            T.ScheduleType AS Schedules_ScheduleType, 
            T.CreationTime AS Schedules_CreationTime, 
            True AS _from0
        FROM DataModelStoreContainer.Schedules AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// Entities.Stops のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView30()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.Stops", "\r\n    SELECT VALUE -- Constructing Stops\r\n        [DataModel.Stops](T1.Stops_Id, " +
                    "T1.Stops_ArriveTime, T1.Stops_Directions, T1.Stops_PathTo, T1.Stops_Distance, T1" +
                    ".Stops_SequenceNumber, T1.Stops_OrderSequenceNumber, T1.Stops_Type, T1.Stops_Tim" +
                    "eAtStop, T1.Stops_TravelTime, T1.Stops_WaitTime, T1.Stops_Locked) WITH \r\n       " +
                    " RELATIONSHIP(CREATEREF(Entities.Locations, ROW(T1.[FK_Stops_Locations.Locations" +
                    ".Id]),[DataModel.Locations]),[DataModel.FK_Stops_Locations],Stops,Locations) \r\n " +
                    "       RELATIONSHIP(CREATEREF(Entities.Orders, ROW(T1.[FK_Stops_Orders.Orders.Id" +
                    "]),[DataModel.Orders]),[DataModel.FK_Stops_Orders],Stops,Orders) \r\n        RELAT" +
                    "IONSHIP(CREATEREF(Entities.Routes, ROW(T1.[FK_Stops_Routes.Routes.Id]),[DataMode" +
                    "l.Routes]),[DataModel.FK_Stops_Routes],Stops,Routes) \r\n    FROM (\r\n        SELEC" +
                    "T \r\n            T.Id AS Stops_Id, \r\n            T.ArriveTime AS Stops_ArriveTime" +
                    ", \r\n            T.Directions AS Stops_Directions, \r\n            T.PathTo AS Stop" +
                    "s_PathTo, \r\n            T.Distance AS Stops_Distance, \r\n            T.SequenceNu" +
                    "mber AS Stops_SequenceNumber, \r\n            T.OrderSequenceNumber AS Stops_Order" +
                    "SequenceNumber, \r\n            T.Type AS Stops_Type, \r\n            T.TimeAtStop A" +
                    "S Stops_TimeAtStop, \r\n            T.TravelTime AS Stops_TravelTime, \r\n          " +
                    "  T.WaitTime AS Stops_WaitTime, \r\n            T.Locked AS Stops_Locked, \r\n      " +
                    "      True AS _from0, \r\n            T.LocationId AS [FK_Stops_Locations.Location" +
                    "s.Id], \r\n            T.OrderId AS [FK_Stops_Orders.Orders.Id], \r\n            T.R" +
                    "outeId AS [FK_Stops_Routes.Routes.Id]\r\n        FROM DataModelStoreContainer.Stop" +
                    "s AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// Entities.Vehicles のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView31()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.Vehicles", @"
    SELECT VALUE -- Constructing Vehicles
        [DataModel.Vehicles](T1.Vehicles_Id, T1.Vehicles_Name, T1.Vehicles_Comment, T1.Vehicles_FixedSalary, T1.Vehicles_FuelConsumption, T1.Vehicles_Capacities, T1.Vehicles_CreationTime, T1.Vehicles_Deleted) WITH 
        RELATIONSHIP(CREATEREF(Entities.FuelTypes, ROW(T1.[FK_Vehicles_FuelTypes.FuelTypes.Id]),[DataModel.FuelTypes]),[DataModel.FK_Vehicles_FuelTypes],Vehicles,FuelTypes) 
        RELATIONSHIP(CREATEREF(Entities.MobileDevices, ROW(T1.[FK_Vehicles_MobileDevices.MobileDevices.Id]),[DataModel.MobileDevices]),[DataModel.FK_Vehicles_MobileDevices],Vehicles,MobileDevices) 
    FROM (
        SELECT 
            T.Id AS Vehicles_Id, 
            T.Name AS Vehicles_Name, 
            T.Comment AS Vehicles_Comment, 
            T.FixedSalary AS Vehicles_FixedSalary, 
            T.FuelConsumption AS Vehicles_FuelConsumption, 
            T.Capacities AS Vehicles_Capacities, 
            T.CreationTime AS Vehicles_CreationTime, 
            T.Deleted AS Vehicles_Deleted, 
            True AS _from0, 
            T.FuelTypeId AS [FK_Vehicles_FuelTypes.FuelTypes.Id], 
            T.MobileDeviceId AS [FK_Vehicles_MobileDevices.MobileDevices.Id]
        FROM DataModelStoreContainer.Vehicles AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// Entities.VehicleSpecialties のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView32()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.VehicleSpecialties", @"
    SELECT VALUE -- Constructing VehicleSpecialties
        [DataModel.VehicleSpecialties](T1.VehicleSpecialties_Id, T1.VehicleSpecialties_Name, T1.VehicleSpecialties_Comment, T1.VehicleSpecialties_CreationTime, T1.VehicleSpecialties_Deleted)
    FROM (
        SELECT 
            T.Id AS VehicleSpecialties_Id, 
            T.Name AS VehicleSpecialties_Name, 
            T.Comment AS VehicleSpecialties_Comment, 
            T.CreationTime AS VehicleSpecialties_CreationTime, 
            T.Deleted AS VehicleSpecialties_Deleted, 
            True AS _from0
        FROM DataModelStoreContainer.VehicleSpecialties AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// Entities.Zones のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView33()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.Zones", @"
    SELECT VALUE -- Constructing Zones
        [DataModel.Zones](T1.Zones_Id, T1.Zones_Name, T1.Zones_Comment, T1.Zones_Geometry, T1.Zones_CreationTime, T1.Zones_Deleted)
    FROM (
        SELECT 
            T.Id AS Zones_Id, 
            T.Name AS Zones_Name, 
            T.Comment AS Zones_Comment, 
            T.Geometry AS Zones_Geometry, 
            T.CreationTime AS Zones_CreationTime, 
            T.Deleted AS Zones_Deleted, 
            True AS _from0
        FROM DataModelStoreContainer.Zones AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// Entities.FK_Drivers_MobileDevices のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView34()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.FK_Drivers_MobileDevices", @"
    SELECT VALUE -- Constructing FK_Drivers_MobileDevices
        [DataModel.FK_Drivers_MobileDevices](T3.[FK_Drivers_MobileDevices.MobileDevices], T3.[FK_Drivers_MobileDevices.Drivers])
    FROM (
        SELECT -- Constructing MobileDevices
            CreateRef(Entities.MobileDevices, row(T2.[FK_Drivers_MobileDevices.MobileDevices.Id]),[DataModel.MobileDevices]) AS [FK_Drivers_MobileDevices.MobileDevices], 
            T2.[FK_Drivers_MobileDevices.Drivers]
        FROM (
            SELECT -- Constructing Drivers
                CreateRef(Entities.Drivers, row(T1.[FK_Drivers_MobileDevices.Drivers.Id]),[DataModel.Drivers]) AS [FK_Drivers_MobileDevices.Drivers], 
                T1.[FK_Drivers_MobileDevices.MobileDevices.Id]
            FROM (
                SELECT 
                    T.MobileDeviceId AS [FK_Drivers_MobileDevices.MobileDevices.Id], 
                    T.Id AS [FK_Drivers_MobileDevices.Drivers.Id], 
                    True AS _from0
                FROM DataModelStoreContainer.Drivers AS T
                WHERE T.MobileDeviceId IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.FK_Routes_Drivers のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView35()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.FK_Routes_Drivers", @"
    SELECT VALUE -- Constructing FK_Routes_Drivers
        [DataModel.FK_Routes_Drivers](T3.[FK_Routes_Drivers.Drivers], T3.[FK_Routes_Drivers.Routes])
    FROM (
        SELECT -- Constructing Drivers
            CreateRef(Entities.Drivers, row(T2.[FK_Routes_Drivers.Drivers.Id]),[DataModel.Drivers]) AS [FK_Routes_Drivers.Drivers], 
            T2.[FK_Routes_Drivers.Routes]
        FROM (
            SELECT -- Constructing Routes
                CreateRef(Entities.Routes, row(T1.[FK_Routes_Drivers.Routes.Id]),[DataModel.Routes]) AS [FK_Routes_Drivers.Routes], 
                T1.[FK_Routes_Drivers.Drivers.Id]
            FROM (
                SELECT 
                    T.DriversId AS [FK_Routes_Drivers.Drivers.Id], 
                    T.Id AS [FK_Routes_Drivers.Routes.Id], 
                    True AS _from0
                FROM DataModelStoreContainer.Routes AS T
                WHERE T.DriversId IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.FK_Vehicles_FuelTypes のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView36()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.FK_Vehicles_FuelTypes", @"
    SELECT VALUE -- Constructing FK_Vehicles_FuelTypes
        [DataModel.FK_Vehicles_FuelTypes](T3.[FK_Vehicles_FuelTypes.FuelTypes], T3.[FK_Vehicles_FuelTypes.Vehicles])
    FROM (
        SELECT -- Constructing FuelTypes
            CreateRef(Entities.FuelTypes, row(T2.[FK_Vehicles_FuelTypes.FuelTypes.Id]),[DataModel.FuelTypes]) AS [FK_Vehicles_FuelTypes.FuelTypes], 
            T2.[FK_Vehicles_FuelTypes.Vehicles]
        FROM (
            SELECT -- Constructing Vehicles
                CreateRef(Entities.Vehicles, row(T1.[FK_Vehicles_FuelTypes.Vehicles.Id]),[DataModel.Vehicles]) AS [FK_Vehicles_FuelTypes.Vehicles], 
                T1.[FK_Vehicles_FuelTypes.FuelTypes.Id]
            FROM (
                SELECT 
                    T.FuelTypeId AS [FK_Vehicles_FuelTypes.FuelTypes.Id], 
                    T.Id AS [FK_Vehicles_FuelTypes.Vehicles.Id], 
                    True AS _from0
                FROM DataModelStoreContainer.Vehicles AS T
                WHERE T.FuelTypeId IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.FK_Routes_EndLocations のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView37()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.FK_Routes_EndLocations", @"
    SELECT VALUE -- Constructing FK_Routes_EndLocations
        [DataModel.FK_Routes_EndLocations](T3.[FK_Routes_EndLocations.Locations], T3.[FK_Routes_EndLocations.Routes])
    FROM (
        SELECT -- Constructing Locations
            CreateRef(Entities.Locations, row(T2.[FK_Routes_EndLocations.Locations.Id]),[DataModel.Locations]) AS [FK_Routes_EndLocations.Locations], 
            T2.[FK_Routes_EndLocations.Routes]
        FROM (
            SELECT -- Constructing Routes
                CreateRef(Entities.Routes, row(T1.[FK_Routes_EndLocations.Routes.Id]),[DataModel.Routes]) AS [FK_Routes_EndLocations.Routes], 
                T1.[FK_Routes_EndLocations.Locations.Id]
            FROM (
                SELECT 
                    T.EndLocationId AS [FK_Routes_EndLocations.Locations.Id], 
                    T.Id AS [FK_Routes_EndLocations.Routes.Id], 
                    True AS _from0
                FROM DataModelStoreContainer.Routes AS T
                WHERE T.EndLocationId IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.FK_Routes_StartLocations のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView38()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.FK_Routes_StartLocations", @"
    SELECT VALUE -- Constructing FK_Routes_StartLocations
        [DataModel.FK_Routes_StartLocations](T3.[FK_Routes_StartLocations.Locations], T3.[FK_Routes_StartLocations.Routes])
    FROM (
        SELECT -- Constructing Locations
            CreateRef(Entities.Locations, row(T2.[FK_Routes_StartLocations.Locations.Id]),[DataModel.Locations]) AS [FK_Routes_StartLocations.Locations], 
            T2.[FK_Routes_StartLocations.Routes]
        FROM (
            SELECT -- Constructing Routes
                CreateRef(Entities.Routes, row(T1.[FK_Routes_StartLocations.Routes.Id]),[DataModel.Routes]) AS [FK_Routes_StartLocations.Routes], 
                T1.[FK_Routes_StartLocations.Locations.Id]
            FROM (
                SELECT 
                    T.StartLocationId AS [FK_Routes_StartLocations.Locations.Id], 
                    T.Id AS [FK_Routes_StartLocations.Routes.Id], 
                    True AS _from0
                FROM DataModelStoreContainer.Routes AS T
                WHERE T.StartLocationId IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.FK_Stops_Locations のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView39()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.FK_Stops_Locations", @"
    SELECT VALUE -- Constructing FK_Stops_Locations
        [DataModel.FK_Stops_Locations](T3.[FK_Stops_Locations.Locations], T3.[FK_Stops_Locations.Stops])
    FROM (
        SELECT -- Constructing Locations
            CreateRef(Entities.Locations, row(T2.[FK_Stops_Locations.Locations.Id]),[DataModel.Locations]) AS [FK_Stops_Locations.Locations], 
            T2.[FK_Stops_Locations.Stops]
        FROM (
            SELECT -- Constructing Stops
                CreateRef(Entities.Stops, row(T1.[FK_Stops_Locations.Stops.Id]),[DataModel.Stops]) AS [FK_Stops_Locations.Stops], 
                T1.[FK_Stops_Locations.Locations.Id]
            FROM (
                SELECT 
                    T.LocationId AS [FK_Stops_Locations.Locations.Id], 
                    T.Id AS [FK_Stops_Locations.Stops.Id], 
                    True AS _from0
                FROM DataModelStoreContainer.Stops AS T
                WHERE T.LocationId IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.FK_Vehicles_MobileDevices のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView40()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.FK_Vehicles_MobileDevices", @"
    SELECT VALUE -- Constructing FK_Vehicles_MobileDevices
        [DataModel.FK_Vehicles_MobileDevices](T3.[FK_Vehicles_MobileDevices.MobileDevices], T3.[FK_Vehicles_MobileDevices.Vehicles])
    FROM (
        SELECT -- Constructing MobileDevices
            CreateRef(Entities.MobileDevices, row(T2.[FK_Vehicles_MobileDevices.MobileDevices.Id]),[DataModel.MobileDevices]) AS [FK_Vehicles_MobileDevices.MobileDevices], 
            T2.[FK_Vehicles_MobileDevices.Vehicles]
        FROM (
            SELECT -- Constructing Vehicles
                CreateRef(Entities.Vehicles, row(T1.[FK_Vehicles_MobileDevices.Vehicles.Id]),[DataModel.Vehicles]) AS [FK_Vehicles_MobileDevices.Vehicles], 
                T1.[FK_Vehicles_MobileDevices.MobileDevices.Id]
            FROM (
                SELECT 
                    T.MobileDeviceId AS [FK_Vehicles_MobileDevices.MobileDevices.Id], 
                    T.Id AS [FK_Vehicles_MobileDevices.Vehicles.Id], 
                    True AS _from0
                FROM DataModelStoreContainer.Vehicles AS T
                WHERE T.MobileDeviceId IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.FK_Stops_Orders のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView41()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.FK_Stops_Orders", @"
    SELECT VALUE -- Constructing FK_Stops_Orders
        [DataModel.FK_Stops_Orders](T3.[FK_Stops_Orders.Orders], T3.[FK_Stops_Orders.Stops])
    FROM (
        SELECT -- Constructing Orders
            CreateRef(Entities.Orders, row(T2.[FK_Stops_Orders.Orders.Id]),[DataModel.Orders]) AS [FK_Stops_Orders.Orders], 
            T2.[FK_Stops_Orders.Stops]
        FROM (
            SELECT -- Constructing Stops
                CreateRef(Entities.Stops, row(T1.[FK_Stops_Orders.Stops.Id]),[DataModel.Stops]) AS [FK_Stops_Orders.Stops], 
                T1.[FK_Stops_Orders.Orders.Id]
            FROM (
                SELECT 
                    T.OrderId AS [FK_Stops_Orders.Orders.Id], 
                    T.Id AS [FK_Stops_Orders.Stops.Id], 
                    True AS _from0
                FROM DataModelStoreContainer.Stops AS T
                WHERE T.OrderId IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.FK_Routes_Schedules のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView42()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.FK_Routes_Schedules", @"
    SELECT VALUE -- Constructing FK_Routes_Schedules
        [DataModel.FK_Routes_Schedules](T3.[FK_Routes_Schedules.Schedules], T3.[FK_Routes_Schedules.Routes])
    FROM (
        SELECT -- Constructing Schedules
            CreateRef(Entities.Schedules, row(T2.[FK_Routes_Schedules.Schedules.Id]),[DataModel.Schedules]) AS [FK_Routes_Schedules.Schedules], 
            T2.[FK_Routes_Schedules.Routes]
        FROM (
            SELECT -- Constructing Routes
                CreateRef(Entities.Routes, row(T1.[FK_Routes_Schedules.Routes.Id]),[DataModel.Routes]) AS [FK_Routes_Schedules.Routes], 
                T1.[FK_Routes_Schedules.Schedules.Id]
            FROM (
                SELECT 
                    T.ScheduleId AS [FK_Routes_Schedules.Schedules.Id], 
                    T.Id AS [FK_Routes_Schedules.Routes.Id], 
                    True AS _from0
                FROM DataModelStoreContainer.Routes AS T
                WHERE T.ScheduleId IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.FK_Routes_Vehicles のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView43()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.FK_Routes_Vehicles", @"
    SELECT VALUE -- Constructing FK_Routes_Vehicles
        [DataModel.FK_Routes_Vehicles](T3.[FK_Routes_Vehicles.Vehicles], T3.[FK_Routes_Vehicles.Routes])
    FROM (
        SELECT -- Constructing Vehicles
            CreateRef(Entities.Vehicles, row(T2.[FK_Routes_Vehicles.Vehicles.Id]),[DataModel.Vehicles]) AS [FK_Routes_Vehicles.Vehicles], 
            T2.[FK_Routes_Vehicles.Routes]
        FROM (
            SELECT -- Constructing Routes
                CreateRef(Entities.Routes, row(T1.[FK_Routes_Vehicles.Routes.Id]),[DataModel.Routes]) AS [FK_Routes_Vehicles.Routes], 
                T1.[FK_Routes_Vehicles.Vehicles.Id]
            FROM (
                SELECT 
                    T.VehiclesId AS [FK_Routes_Vehicles.Vehicles.Id], 
                    T.Id AS [FK_Routes_Vehicles.Routes.Id], 
                    True AS _from0
                FROM DataModelStoreContainer.Routes AS T
                WHERE T.VehiclesId IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.FK_Stops_Routes のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView44()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.FK_Stops_Routes", @"
    SELECT VALUE -- Constructing FK_Stops_Routes
        [DataModel.FK_Stops_Routes](T3.[FK_Stops_Routes.Routes], T3.[FK_Stops_Routes.Stops])
    FROM (
        SELECT -- Constructing Routes
            CreateRef(Entities.Routes, row(T2.[FK_Stops_Routes.Routes.Id]),[DataModel.Routes]) AS [FK_Stops_Routes.Routes], 
            T2.[FK_Stops_Routes.Stops]
        FROM (
            SELECT -- Constructing Stops
                CreateRef(Entities.Stops, row(T1.[FK_Stops_Routes.Stops.Id]),[DataModel.Stops]) AS [FK_Stops_Routes.Stops], 
                T1.[FK_Stops_Routes.Routes.Id]
            FROM (
                SELECT 
                    T.RouteId AS [FK_Stops_Routes.Routes.Id], 
                    T.Id AS [FK_Stops_Routes.Stops.Id], 
                    True AS _from0
                FROM DataModelStoreContainer.Stops AS T
                WHERE T.RouteId IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.DriverDriverSpecialties のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView45()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.DriverDriverSpecialties", @"
    SELECT VALUE -- Constructing DriverDriverSpecialties
        [DataModel.DriverDriverSpecialties](T3.DriverDriverSpecialties_Drivers, T3.DriverDriverSpecialties_DriverSpecialties)
    FROM (
        SELECT -- Constructing Drivers
            CreateRef(Entities.Drivers, row(T2.DriverDriverSpecialties_Drivers_Id),[DataModel.Drivers]) AS DriverDriverSpecialties_Drivers, 
            T2.DriverDriverSpecialties_DriverSpecialties
        FROM (
            SELECT -- Constructing DriverSpecialties
                CreateRef(Entities.DriverSpecialties, row(T1.DriverDriverSpecialties_DriverSpecialties_Id),[DataModel.DriverSpecialties]) AS DriverDriverSpecialties_DriverSpecialties, 
                T1.DriverDriverSpecialties_Drivers_Id
            FROM (
                SELECT 
                    T.DriverId AS DriverDriverSpecialties_Drivers_Id, 
                    T.DriverSpecialtyId AS DriverDriverSpecialties_DriverSpecialties_Id, 
                    True AS _from0
                FROM DataModelStoreContainer.DriverDriverSpecialties AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.OrderDriverSpecialties のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView46()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.OrderDriverSpecialties", @"
    SELECT VALUE -- Constructing OrderDriverSpecialties
        [DataModel.OrderDriverSpecialties](T3.OrderDriverSpecialties_DriverSpecialties, T3.OrderDriverSpecialties_Orders)
    FROM (
        SELECT -- Constructing DriverSpecialties
            CreateRef(Entities.DriverSpecialties, row(T2.OrderDriverSpecialties_DriverSpecialties_Id),[DataModel.DriverSpecialties]) AS OrderDriverSpecialties_DriverSpecialties, 
            T2.OrderDriverSpecialties_Orders
        FROM (
            SELECT -- Constructing Orders
                CreateRef(Entities.Orders, row(T1.OrderDriverSpecialties_Orders_Id),[DataModel.Orders]) AS OrderDriverSpecialties_Orders, 
                T1.OrderDriverSpecialties_DriverSpecialties_Id
            FROM (
                SELECT 
                    T.DriverSpecialtyId AS OrderDriverSpecialties_DriverSpecialties_Id, 
                    T.OrderId AS OrderDriverSpecialties_Orders_Id, 
                    True AS _from0
                FROM DataModelStoreContainer.OrderDriverSpecialties AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.OrderVehicleSpecialties のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView47()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.OrderVehicleSpecialties", @"
    SELECT VALUE -- Constructing OrderVehicleSpecialties
        [DataModel.OrderVehicleSpecialties](T3.OrderVehicleSpecialties_Orders, T3.OrderVehicleSpecialties_VehicleSpecialties)
    FROM (
        SELECT -- Constructing Orders
            CreateRef(Entities.Orders, row(T2.OrderVehicleSpecialties_Orders_Id),[DataModel.Orders]) AS OrderVehicleSpecialties_Orders, 
            T2.OrderVehicleSpecialties_VehicleSpecialties
        FROM (
            SELECT -- Constructing VehicleSpecialties
                CreateRef(Entities.VehicleSpecialties, row(T1.OrderVehicleSpecialties_VehicleSpecialties_Id),[DataModel.VehicleSpecialties]) AS OrderVehicleSpecialties_VehicleSpecialties, 
                T1.OrderVehicleSpecialties_Orders_Id
            FROM (
                SELECT 
                    T.OrderId AS OrderVehicleSpecialties_Orders_Id, 
                    T.VehicleSpecialtyId AS OrderVehicleSpecialties_VehicleSpecialties_Id, 
                    True AS _from0
                FROM DataModelStoreContainer.OrderVehicleSpecialties AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.RenewalLocations のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView48()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.RenewalLocations", @"
    SELECT VALUE -- Constructing RenewalLocations
        [DataModel.RenewalLocations](T3.RenewalLocations_Locations, T3.RenewalLocations_Routes)
    FROM (
        SELECT -- Constructing Locations
            CreateRef(Entities.Locations, row(T2.RenewalLocations_Locations_Id),[DataModel.Locations]) AS RenewalLocations_Locations, 
            T2.RenewalLocations_Routes
        FROM (
            SELECT -- Constructing Routes
                CreateRef(Entities.Routes, row(T1.RenewalLocations_Routes_Id),[DataModel.Routes]) AS RenewalLocations_Routes, 
                T1.RenewalLocations_Locations_Id
            FROM (
                SELECT 
                    T.LocationId AS RenewalLocations_Locations_Id, 
                    T.RouteId AS RenewalLocations_Routes_Id, 
                    True AS _from0
                FROM DataModelStoreContainer.RenewalLocations AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.RouteZones のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView49()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.RouteZones", @"
    SELECT VALUE -- Constructing RouteZones
        [DataModel.RouteZones](T3.RouteZones_Routes, T3.RouteZones_Zones)
    FROM (
        SELECT -- Constructing Routes
            CreateRef(Entities.Routes, row(T2.RouteZones_Routes_Id),[DataModel.Routes]) AS RouteZones_Routes, 
            T2.RouteZones_Zones
        FROM (
            SELECT -- Constructing Zones
                CreateRef(Entities.Zones, row(T1.RouteZones_Zones_Id),[DataModel.Zones]) AS RouteZones_Zones, 
                T1.RouteZones_Routes_Id
            FROM (
                SELECT 
                    T.RouteId AS RouteZones_Routes_Id, 
                    T.ZoneId AS RouteZones_Zones_Id, 
                    True AS _from0
                FROM DataModelStoreContainer.RouteZones AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// Entities.VehicleVehicleSpecialties のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView50()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.VehicleVehicleSpecialties", @"
    SELECT VALUE -- Constructing VehicleVehicleSpecialties
        [DataModel.VehicleVehicleSpecialties](T3.VehicleVehicleSpecialties_Vehicles, T3.VehicleVehicleSpecialties_VehicleSpecialties)
    FROM (
        SELECT -- Constructing Vehicles
            CreateRef(Entities.Vehicles, row(T2.VehicleVehicleSpecialties_Vehicles_Id),[DataModel.Vehicles]) AS VehicleVehicleSpecialties_Vehicles, 
            T2.VehicleVehicleSpecialties_VehicleSpecialties
        FROM (
            SELECT -- Constructing VehicleSpecialties
                CreateRef(Entities.VehicleSpecialties, row(T1.VehicleVehicleSpecialties_VehicleSpecialties_Id),[DataModel.VehicleSpecialties]) AS VehicleVehicleSpecialties_VehicleSpecialties, 
                T1.VehicleVehicleSpecialties_Vehicles_Id
            FROM (
                SELECT 
                    T.VehicleId AS VehicleVehicleSpecialties_Vehicles_Id, 
                    T.VehicleSpecialtyId AS VehicleVehicleSpecialties_VehicleSpecialties_Id, 
                    True AS _from0
                FROM DataModelStoreContainer.VehicleVehicleSpecialties AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// DataModelStoreContainer.Project のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView51()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DataModelStoreContainer.Project", @"
    SELECT VALUE -- Constructing Project
        [DataModel.Store.Project](T1.Project_Id, T1.Project_Version)
    FROM (
        SELECT 
            T.Id AS Project_Id, 
            T.Version AS Project_Version, 
            True AS _from0
        FROM Entities.Project AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// Entities.Project のビューを返します
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView52()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.Project", @"
    SELECT VALUE -- Constructing Project
        [DataModel.Project](T1.Project_Id, T1.Project_Version)
    FROM (
        SELECT 
            T.Id AS Project_Id, 
            T.Version AS Project_Version, 
            True AS _from0
        FROM DataModelStoreContainer.Project AS T
    ) AS T1");
        }
    }
}
